export const CartActionTypes = {
    TOGGLE_CART_ITEMS: 'TOGGLE_CART_ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    REDUCE_QUANTITY: 'REDUCE_QUANTITY',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART'
}
